# Generated by Django 5.1.4 on 2024-12-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
