# Generated by Django 5.1.4 on 2025-01-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedtime',
            name='length',
            field=models.IntegerField(),
        ),
    ]
