name: TimeScheduler

services:
  mysql-primary:
    image: mysql:latest
    container_name: mysql-primary
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timescheduler
      MYSQL_TCP_PORT: 50400
    ports: 
      - "50400:50400"
    volumes:
      - master_data:/var/lib/mysql
    networks:
      - db_network

  mysql-replica:
    image: mysql:latest
    container_name: mysql-replica
    depends_on:
      - mysql-primary
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timescheduler
      MYSQL_TCP_PORT: 50401
    ports: 
      - "50401:50401"
    volumes:
      - slave_data:/var/lib/mysql
    networks:
      - db_network

  backup:
    image: debian:latest
    container_name: backup_service
    depends_on:
      - mysql-primary
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - backupy:/backup
    command: >
      bash -c "apt update && apt install -y default-mysql-client cron &&  # Instalacja narzędzi mysqldump i cron
              mkdir -p /etc/cron.d &&  # Tworzenie katalogu cron.d, jeśli nie istnieje
              echo '* * * * * root mysqldump -h 172.18.0.2 -u root -proot --port=50400 timescheduler > /backup/db_backup.sql' > /etc/cron.d/backup &&  # Zadanie cron do wykonywania kopii zapasowej co minutę
              chmod 0644 /etc/cron.d/backup && 
              crontab /etc/cron.d/backup &&  
              cron -f"  # Uruchomienie demona cron
    networks:
      - db_network

volumes:
  master_data:
  slave_data:
  backupy:

networks:
  db_network: